### ISSUE TITLE
The dropped filed sometimes gets duplicated

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mFiles#11]

**Comment by kumardurgesh91** [comment]
Hello,
Please provide me more detail. I tried many times but did not get this issue.

**Comment by LAlexMHllc** [comment]
A file was dropped once, but two entries displayed for the same file.

**Comment by bluenevus** [comment]
Specifically any screenshots would be helpful

## 

Vr Frank

**Comment by LAlexMHllc** [comment]
No screenshot available. If it occurs again, then a screenshot will be taken.
