### ISSUE TITLE
Brand the app

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mFiles#13]
Brand the app with the MicroHealth Logo and use of colors.

![mfiles_brand_app](https://cloud.githubusercontent.com/assets/11938477/11844299/0d33067a-a3dc-11e5-8c1c-1d9b2c22cd51.jpg)

**Comment by kumardurgesh91** [comment]
Hello LAlex,
Please provide me logo in large size so that I can put on top of screen.

**Comment by LAlexMHllc** [comment]
2015_MicroHealth-white.png is in the folder

**Comment by kumardurgesh91** [comment]
Hello LAlex,
I changed the design of project something like above. You may please check and mention changes if you need.
