### ISSUE TITLE
Add "Share" checkbox to each filebox; and add "Share file(s)" button

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mFiles#16]
1. For each filebox, add a checkbox with "Share"
2. Add a button "Share file(s)" that will gather the URL(s) with paired password(s) of the selected files to be included in email. Position to the right of "Add button".

See Issue # 13 Brand the app

**Comment by kumardurgesh91** [comment]
Hi LAlex,
Can you please provide more me little information about this task. The purpose of functionality about to send mail with file attachment. right?

**Comment by LAlexMHllc** [comment]
The user checks all "Share" checkboxes that correspond to the file links that are to be included in a single email
When the "Share files(s)" button is clicked, the email message will contain all of the file links (with corresponding passwords, if any) with a checked corresponding "Share" checkbox.
This way the user will not have to copy/paste all file links (and passwords) into an email message.

**Comment by LAlexMHllc** [comment]
Closing this for elements added.
Opening new issue for functionality.
