### ISSUE TITLE
Add two more Logo sizes based on screen width

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mFiles#20]
Add another MH Logo size between 401 pixels and approx. 504 pixels
Add another MH Logo size between approx. 505 pixels and 640 pixels

Fix MH Logo - too large

![mh_logo_401px](https://cloud.githubusercontent.com/assets/11938477/13084751/b5bb8694-d4a8-11e5-945a-1e3581b6f84a.jpg)

**Comment by kumardurgesh91** [comment]
fixed

**Comment by LAlexMHllc** [comment]
What pixel range was it changed? The issue pixel range looks the same as before. Changes should have been:

Add another MH Logo size between 401 pixels and approx. 504 pixels
Add another MH Logo size between approx. 505 pixels and 640 pixels

**Comment by kumardurgesh91** [comment]
Hello Alex,
Here I am attaching screen shot.
Please let me know if you sill want to reduce logo size.

Thanks
![401](https://cloud.githubusercontent.com/assets/6436947/13548310/5e327b7a-e313-11e5-9007-b8dbbd724916.png)
![504](https://cloud.githubusercontent.com/assets/6436947/13548311/5e35fd68-e313-11e5-90e0-47a107443506.png)
![640](https://cloud.githubusercontent.com/assets/6436947/13548312/5e396ed0-e313-11e5-8b09-74aee91fff29.png)

**Comment by LAlexMHllc** [comment]
The MH logo size looks the same on your localhost screenshots, but they fit, so it's fine.
